export const FETCH_PLACEHOLDER_DATA = 'FETCH_PLACEHOLDER_DATA'
export const FETCH_PLACEHOLDER_DATA_SUCCESS = 'FETCH_PLACEHOLDER_DATA_SUCCESS'
export const FETCH_PLACEHOLDER_DATA_ERROR = 'FETCH_PLACEHOLDER_DATA_ERROR'

export const FETCH_POST = 'FETCH_POST'
export const FETCH_POST_SUCCESS = 'FETCH_POST_SUCCESS'
export const FETCH_POST_ERROR = 'FETCH_POST_ERROR'