export const FETCH_PLACEHOLDER_DATA = 'FETCH_PLACEHOLDER_DATA'
export const FETCH_PLACEHOLDER_DATA_SUCCESS = 'FETCH_PLACEHOLDER_DATA_SUCCESS'
export const FETCH_PLACEHOLDER_DATA_ERROR = 'FETCH_PLACEHOLDER_DATA_ERROR'